# Setup
title:               GenoCat Theme
tagline:             'A Jekyll theme'
description:         'A database of genomic visualization tools.'
url:                 'http://127.0.0.1:4000'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Gehlenborg Lab
  url:               https://github.com/hms-dbmi/genocat
  email:             nils@hms.harvard.edu

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Custom vars
version:             1.0.0
# google_analytics_id: #UA-XXXX-Y
